#!/bin/bash
cd $(dirname $0)
. ./enviroment
curl  https://api.coreserver.jp/v1/cms/phpadmin_check -X POST \
  -d "api_secret_key=${API_SECRET_KEY}" \
  -d "server_name=${SERVER_NAME}" \
  -d "account=${ACCOUNT}"
