#!/bin/bash
. ./enviroment
curl https://api.coreserver.jp/v1/tool/ssh_ip_allow -X POST \
  -d "api_secret_key=${API_SECRET_KEY}" \
  -d "server_name=${SERVER_NAME}" \
  -d "account=${ACCOUNT}" \
  -d "param[addr]=${IP_ADDR}"
